apiVersion: v1
kind: ServiceAccount
metadata:
  name: safetyos-sa
  namespace: safetyos
  labels:
    app.kubernetes.io/name: safetyos-sa
    app.kubernetes.io/part-of: safetyos-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: safetyos-role
  namespace: safetyos
  labels:
    app.kubernetes.io/name: safetyos-role
    app.kubernetes.io/part-of: safetyos-platform
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "secrets", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: safetyos-rolebinding
  namespace: safetyos
  labels:
    app.kubernetes.io/name: safetyos-rolebinding
    app.kubernetes.io/part-of: safetyos-platform
subjects:
  - kind: ServiceAccount
    name: safetyos-sa
    namespace: safetyos
roleRef:
  kind: Role
  name: safetyos-role
  apiGroup: rbac.authorization.k8s.io
